### ISSUE TITLE
SFA - Define process for supporting new sample environments in NMDC schema

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#11]
Note: Changes to attributes/fields in schema should be submitted via GitHub

Add links to new process to this issue.

**Comment by pvangay** [comment]
Reassigned to David H.

@dehays - enlisting your help if/when we need to support new environments

**Comment by pvangay** [comment]
looks like the process is to let @dehays @mslarae13 know of next priority environments so that they can start working on the spreadsheets, and making sure the schema can support it. closing this for now.
