### ISSUE TITLE
SFA - Develop metadata templates for new sample environments

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#12]
Please add links to the templates in this issue.

**Comment by mslarae13** [comment]
Prioritization are Sediment and plant, correct?

**Comment by ssarrafan** [comment]
@mslarae13 I checked with @emileyfadrosh and the priority is soil, plant and then sediment in that order.  I hope that helps.  Thank you for all your help.

**Comment by ssarrafan** [comment]
@mslarae13 can this issue be closed?  Or should it be moved to the May sprint?

**Comment by mslarae13** [comment]
@ssarrafan 
I think this issue can be closed. As I've developed the template (minus plants... it's close! just need a few more details). 

Next step / new issue would be confirm template design  & gather feedback on usability

**Comment by mslarae13** [comment]
@ssarrafan  I'll close this ticket.. I dunno how to make a new one. Is it the same as "add a note to this column"?....

**Comment by ssarrafan** [comment]
> @ssarrafan I'll close this ticket.. I dunno how to make a new one. Is it the same as "add a note to this column"?....

@mslarae13 To create a new issue you have to create a note and then convert it to an issue. I'll do it for you.  Thanks for closing this one.
