### ISSUE TITLE
SFA - Schedule initiation calls

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#15]
- [x] Update template for call notes (example [here](https://docs.google.com/document/d/1lAml7Ju35aVtn71ibXwfNs6b71_mLNBTW62-No493bo/edit))

- [ ] Schedule calls in the next 2-4 weeks
- [ ] Summarize discussions, update Collaborator status, identify action items, and next steps

**Comment by mar-rudolph** [comment]
The majority of the calls will happen in the beginning of May, so this can be moved to the May Spring for completion.

**Comment by ssarrafan** [comment]
> The majority of the calls will happen in the beginning of May, so this can be moved to the May Spring for completion.

@mar-rudolph are all the calls scheduled?  If so let's close this for the April sprint and we can add a new issue to have the first round of calls in May.  What do you think?

**Comment by mar-rudolph** [comment]
@ssarrafan Yes, they are! That sounds good to me.

**Comment by ssarrafan** [comment]
Closing ticket per @mar-rudolph
