### ISSUE TITLE
Bioscales - Follow up on availability of data from Oregon

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#17]
Stan was going to find out when the data from Oregon would be available because the goal is to use this data and not sample data.

**Comment by ssarrafan** [comment]
I invited Stan to GitHub and will re-assign this to him once he joins.

**Comment by StantonMartin** [comment]
Assignment complete, closing

**Comment by ssarrafan** [comment]
@StantonMartin thank you for closing this ticket.  Does this mean that the Oregon data is available and you're able to use it?
