### ISSUE TITLE
Bioscales - Figure out viability of processing JGI metabolomics data through EMSL pipelines

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#18]
Kjiersten will facilitate and help figure this out with Yuri and Trent.

**Comment by ssarrafan** [comment]
@corilo any update on this?  Kjiersten said to check with you and see if you've had your meeting with Trent yet.

**Comment by corilo** [comment]
@kfagnan @ssarrafan Yes, they have not yet collect any data for the SFA project. Trent had agreed to provide the raw data for us to process using the NMDC workflow. Instrument (LC-MS) and analysis type are compatible with our the current workflow development and it should not be a problem.

**Comment by kfagnan** [comment]
@yuri, that’s great, thank you!
