### ISSUE TITLE
Bioscales - Create NMDC JSON file focusing on bio sample class and fields

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#19]
Stan is working on creating an NMDC JSON file for the Bioscales project. Add more details and links here.

**Comment by ssarrafan** [comment]
I will re-assign to Stan once he joins NMDC GitHub.  @wdduncan I hope it's ok to leave you on this ticket for now.

**Comment by StantonMartin** [comment]
Initiial data is pushed to 
https://fair.ornl.gov/NMDC/NMDC.json
