### ISSUE TITLE
SFA - Define process for ingesting metadata housed at JGI and EMSL

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#21]

**Comment by mslarae13** [comment]
We will meet with SFA PIs to determine the projects & what data they have available. 
David & I will find the data at JGI/EMSL.
Request metadata from the PIs to link JGI and EMSL where matching IDs aren't available.

Similar process to the FICUS, but hopefully smoother!

 https://docs.google.com/document/d/1qgMR47RVeQT01uu6fWyhaVMOOiT5HYo6A39Mr0vLrog/edit#
