### ISSUE TITLE
Outline draft NMDC Identifiers documentation

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#27]
Initial decisions have been made around some NMDC identifiers but a more detailed documentation covering all aspects is required.

**Comment by ssarrafan** [comment]
It's not good practice to add a new issue this late in the sprint.  We'll try not to repeat this bad habit.

**Comment by mslarae13** [comment]
Updates to this: https://microbiomedata.github.io/nmdc-metadata/identifiers/
Correct?
Or is there a google doc to work off?

With only 1.5 weeks left, I'm sure this will land in the next sprint TBH.

**Comment by dehays** [comment]
@mslarae13 I imagine the result will be used to update the existing Identifer section of the NMDC metadata documentation.  I am working from a gDoc: [NMDC Identifiers](https://docs.google.com/document/d/1ZpMbF28bnZBc4qId7Js5I_U_XP8QKr-PHromoBgonPg/edit#heading=h.dkk2mzcyg9wl) with the thinking that that is an easier form in for comments and feedback.

**Comment by ssarrafan** [comment]
@dehays I believe the outline/draft is done.  Is it ok to close this issue?

**Comment by ssarrafan** [comment]
Closing this per @dehays. He will make a new issue to continue work in May.
