### ISSUE TITLE
FICUS Data/PI highlights in newsletter

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#28]
Pajau has some content but needs to get more from PIs.  Goal is to have this content ready for the June newsletter.

**Comment by ssarrafan** [comment]
Moving to June sprint per @pvangay

**Comment by ssarrafan** [comment]
@pvangay @emileyfadrosh can one of you own this issue please so we can have one assignee per issue?

**Comment by pvangay** [comment]
@ssarrafan yep! I just reassigned it to me only thanks!

**Comment by pvangay** [comment]
Data highlights have all been drafted. Some of the content will be incorporated into the study landing pages with the metadata updates. James Stegen's highlight was planned for June newsletter but is dependent on his metadata updates being made.

**Comment by ssarrafan** [comment]
Note per Pajau:  Moved some of this content to the study landing pages already. It’d still be great to get the “testimonials” but today in the engagement sync we talked about how maybe that can be incorporated into the videos Marisa and Julia are working on. basically, i think that the science stories should just get incorporated into the study pages so we can close this GH issue.
