### ISSUE TITLE
Further develop engagement strategy plan

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#33]
Review and finalize engagement strategy plan.

**Comment by ssarrafan** [comment]
@pvangay @emileyfadrosh @mar-rudolph can one of you own this issue so we can try to have issues assigned to one person at a time?

**Comment by emileyfadrosh** [comment]
I'll own it, we will be setting up brainstorming series week after next.

**Comment by ssarrafan** [comment]
@emileyfadrosh reported that the brainstorming meeting is scheduled.  Also asked to rename this issue as one to develop instead of finalize the plan.

**Comment by emileyfadrosh** [comment]
Held first brainstorming meeting on the 25th to identify strategic objectives. Will continue to develop in subsequent engagement strategy meetings and with leadership team.
