### ISSUE TITLE
Finalize and document milestones for Edge

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#35]
Bin will document the milestones for Edge in May.

**Comment by hubin-keio** [comment]
Acquire computing resources from the San Diego Supercomputing Center (SDSC) (Done)
-VM
-HPC
-Domain registration (edge-nmdc.org)
Test the SDSC computing environment for setting up EDGE NMDC:
-Check shared file system access between VM and HPC (May 17)
-Install back-end components (Java, database, Cromwell, etc.) (May 21)
-Deploy EDGE NMDC (May 27)
Test EDGE NMDC deployment
-Test individual workflows in metaG (June 3)
-Test metaT workflow (June 9)
-Test metaG end-to-end workflows (June 11)
-Address any bug-fixes, essential UI updates (June 18)
-Public beta-testing starts (June 21)
-Public beta-testing ends (July 30)
Adding metaP workflow (July 30)
Adding metaM workflows (TBD, likely 2022 for all metaM workflows)
