### ISSUE TITLE
Scope out the next phase of partnership with NCBI re: training

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#36]
This is to scope out the next phase of NCBI partnership including links back to NMDC training materials, custom NMDC fields at NCBI, etc.

**Comment by ssarrafan** [comment]
Moving to the June sprint per @elishawc

**Comment by elishawc** [comment]
training meetings with stakeholders on Jun 2 and 3

**Comment by elishawc** [comment]
work left - polish up the slide deck, work with @mslarae13 to build out a virtual activity based on the templates and data in system, schedule another call for end of June (with Kayd's help) for final review and practice run.

**Comment by elishawc** [comment]
Finally - MIxS v6 is expected to be formally announced in July, with NCBI SRA and EBI ENA submission supported by the end of 2021.
