### ISSUE TITLE
Website updates: LOS form; Fact Sheet & Media package

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#37]
Website updates by Emiley and Pajau

**Comment by pvangay** [comment]
Also add DMP best practices that @mar-rudolph is working on

**Comment by ssarrafan** [comment]
Moving to June sprint per @pvangay

**Comment by ssarrafan** [comment]
@pvangay and @emileyfadrosh can one of you own this issue so we can try to have only 1 person at a time on GitHub issues?

**Comment by pvangay** [comment]
@ssarrafan i just reassigned it to me - thx!

**Comment by pvangay** [comment]
Draft LOS form [here](https://docs.google.com/document/d/1jb5m-DvZ4BVXAEbSY807aXBxG8cvYwh4KypZYW1Sxzk/edit#)

**Comment by pvangay** [comment]
Added a LOS request form
Added links to 1-slide and 9-slide presentation templates, 2 recorded youtube videos, and a fact sheet under /Resources
Added Marisa's DMP
