### ISSUE TITLE
NMDC Data Management Best Practices

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#39]
Have high-level recommendations for researchers and guidance to funder for what the NMDC can provide

**Comment by mar-rudolph** [comment]
DMP Best Practices draft complete, just needs one more review & to be put on the website [https://docs.google.com/document/d/1HZ6A0nO50Zo-Q14MUDnIfAIgzOkfq2iPEjJALW9XBAA/edit#](url)
