### ISSUE TITLE
SFA - BFI SFA: Bacterial Fungal Interactions and Their Role in Soil Functioning

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#44]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

**Comment by ssarrafan** [comment]
Moving to June sprint per @pvangay

**Comment by pvangay** [comment]
Per conversation with @emileyfadrosh, we'll reconnect with this SFA when they have data available.
