### ISSUE TITLE
SFA - BCA: Biogeochemistry of Actinides

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#45]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

**Comment by pvangay** [comment]
Met on 4/30/21. Mostly amplicon data at the moment. TBD metaT and metaG data coming later. Recommendation is to have them contact us again when they've generated other omic types. 

[Preliminary Data](https://docs.google.com/spreadsheets/d/1yNr4VgnMSvh8_rv2hHRm_-DntWnDCHEo92iJKXVK504/edit#gid=0)
[Initiation Call Notes](url)

Next steps: Pajau to email with recommendation, provide NMDC sediment and water templates (pending @mslarae13 approval).

**Comment by ssarrafan** [comment]
Moving to June sprint per @pvangay

**Comment by mslarae13** [comment]
@pvangay  Looks like this SFA project is a no for now? Am I understanding the above comment correctly... I should send them our metadata template for their reference & request they let me know when more data is available?

**Comment by pvangay** [comment]
Emailed PIs with link to template. Suggested following up with us again when they have data ready.
