### ISSUE TITLE
SFA - MP: Microbes Persist: Systems Biology of the Soil Microbiome

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#46]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

Adding for FYI: @mslarae13 @emileyfadrosh @corilo @SamuelPurvine @dehays @elishawc @mar-rudolph @kfagnan

**Comment by pvangay** [comment]
[Prelim Data](https://docs.google.com/spreadsheets/d/13cCR2iNy2l4ZgXr0z5Fk6MZUq_1ThZjSeQj9envBBHA/edit#gid=0)
[Initiation call notes](https://docs.google.com/document/d/1ay_bYnfqyhgFtqoS0f6izfm_28_aQMLSSB4SSYXJQCA/edit)

| Proposal ID| Data Type |
| - | - |
| CSP 502924 | LC-MS Metabolomics |
| EMSL 49804 | Metaproteomics |
| EMSL 49804 | FT-MS Natural Organic Matter |
| CSP 502924 | Metagenome | 

@corilo @SamuelPurvine confirming that we can accept their metaB and metaP data? (metaB from Trent's group)

@mslarae13 do you have all of the information you need to move forward with sorting out their sample metadata?

If all looks good, I'll be sending a followup email to JP and her group to let them know that we're moving forward, and for them to expect an email from @mslarae13 about additional sample metadata needs.

**Comment by pvangay** [comment]
@jagadishcs Please review their data in GOLD (Proposal ID: CSP 502924) and work with @mslarae13 to make sure that we have all of the required sample metadata for NMDC. Thanks!

**Comment by ssarrafan** [comment]
Second part of this work being documented at https://github.com/microbiomedata/NMDC_Planning/issues/64 for June

**Comment by jagadishcs** [comment]
@pvangay
Reviewed the biosamples of CSP 502924 and shared with GOLD for update.
