### ISSUE TITLE
SFA - SPRUCE: Spruce and Peatland Responses Under Changing Environments

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#47]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

Adding for FYI: @mslarae13 @emileyfadrosh @corilo @SamuelPurvine @dehays @elishawc @mar-rudolph @kfagnan

**Comment by pvangay** [comment]
Expecting multi-omics data generated by both EMSL and JGI from their 2015-2016 dataset on Spaghnum peat moss. Sam and Montana are very familiar with this dataset already. 

Next steps:
@mar-rudolph to follow up with Joel on his other dataset that he's ready to share (with Susannah Tringe)
@mar-rudolph to follow up with David Weston on his dataset that he might want to share
@SamuelPurvine @mslarae13 @dehays @corilo to identify the datasets at the respective facilities and determine what other information we need from the Collaborators.

**Comment by pvangay** [comment]
@dehays do these [metaG JGI project IDs](https://docs.google.com/spreadsheets/d/14l6ibtWrA_B9Q14T--x7grSYa_wnNSZF/edit#gid=1323652308) look correct? 

@SamuelPurvine @corilo they didn't provide us with any EMSL project or proposal IDs but wanted to make sure you weren't already familiar with their datasets. 

Please let me know and I'll make sure to request this info in my followup email to them.

**Comment by ssarrafan** [comment]
Next steps for this will be documented at https://github.com/microbiomedata/NMDC_Planning/issues/66 in June
