### ISSUE TITLE
SFA - PCEF - Persistence Control of Engineered Functions in Complex Soil Microbiomes

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#48]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

**Comment by pvangay** [comment]
This is a new SFA that was established in the last 6 months. Proposed during initiation call to follow up with the NMDC when they have data ready. Met with them jointly with the PNNL Soils SFA group.

[Link to docs](https://drive.google.com/drive/folders/1EdHpD67zipBEtHICLdkgJnnYHAoL90xK?usp=sharing)

**Comment by ssarrafan** [comment]
Moving to June sprint per @pvangay

**Comment by pvangay** [comment]
Emailed PIs with link to template. Suggested following up with us again when they have data ready.
