### ISSUE TITLE
SFA - PNNL Soils SFA

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#49]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

Adding for FYI: @mslarae13 @emileyfadrosh @corilo @SamuelPurvine @dehays @elishawc @mar-rudolph @kfagnan

**Comment by pvangay** [comment]
Have multiple datasets with multiomic data available (as well as in the near future). Locations are primarily in PNNL's data hub, but there is possibility that some data is at NCBI or other community repos.

[link to notes and prelim data](https://drive.google.com/drive/folders/1vEi5Ai8iDJTYU1TYyp916r2z_GnnPWS7?usp=sharing)

Next steps:
@mslarae13 to work with Lindsey to identify public (or soon to be public) datasets
@pvangay @mslarae13 @dehays to meet with Lindsey to review prelim data spreadsheet in detail next week to understand all of the relationships between the data available.

**Comment by pvangay** [comment]
Available datasets [here](https://drive.google.com/file/d/1PtflPaKpcGex_b-6L2DFbjUJik5mQeSL/view?usp=sharing) - see 2nd tab

**Comment by ssarrafan** [comment]
Next steps for June will be documented at https://github.com/microbiomedata/NMDC_Planning/issues/63
