### ISSUE TITLE
SFA - PMI: Plant-Microbe Interfaces

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#50]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

Adding for FYI: @mslarae13 @emileyfadrosh @corilo @SamuelPurvine @dehays @elishawc @mar-rudolph @kfagnan

**Comment by pvangay** [comment]
[Preliminary Data](https://docs.google.com/spreadsheets/d/1z7liwgEKzVaGKtxMKHpWQJiVzuOmSrhDdOKuMwNcEdU/edit#gid=0)
[Initiation call notes](https://docs.google.com/document/d/1zYyaFV-Cxw0oufsSkgUUwJ2gchhTj-zX2VD_3ChFkUI/edit)

30 metaG and amplicon data, host genome data

Mentioned during call that likely will not be prioritized at this time.

**Comment by ssarrafan** [comment]
Next step for this will be documented at https://github.com/microbiomedata/NMDC_Planning/issues/65 for June
