### ISSUE TITLE
SFA - SEED: Secure Ecosystem Engineering and Design

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#51]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

Adding for FYI: @mslarae13 @emileyfadrosh @corilo @SamuelPurvine @dehays @elishawc @mar-rudolph @kfagnan

**Comment by pvangay** [comment]
Expecting metaG, metaT, metaP, amplicon, metaB data - timeline is at least 1 year from now. Recommendation is send plant-asso templates and ask them to follow up with us when ready.

[Call Notes](https://docs.google.com/document/d/1FgkAF5mPRVUykGiReKO9ClURVqHdcA-5ByxRpIawQYs/edit)

**Comment by ssarrafan** [comment]
Moving to June sprint per @pvangay

**Comment by pvangay** [comment]
Emailed PIs with link to template. Suggested following up with us again when they have data ready.
