### ISSUE TITLE
SFA - TES: Terrestrial Ecosystem Science - Belowground Biogeochemistry

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#52]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

Adding for FYI: @mslarae13 @emileyfadrosh @corilo @SamuelPurvine @dehays @elishawc @mar-rudolph @kfagnan

**Comment by pvangay** [comment]
Met today to review datasets. Currently one dataset with metaG and Amplicon data available in SRA. Expecting other multi-omic data at some point in the future but timeline is TBD. There is strong interest in linking between ESS DIVE and KBase - could be a good use case for that. 

[Prelim Data](https://docs.google.com/spreadsheets/d/1H3b7rFMIUs77-SQ15BEWbnVPsunXzAh12bX8Zc0xmM4/edit)
[Call Notes](https://docs.google.com/document/d/11VQghyYb4Cf1kMD0ngB0-T8lqasdH7kUX-HZf92lr3o/edit)

**Comment by pvangay** [comment]
amplicon, metaG data are all currently in [SRA](https://www.ncbi.nlm.nih.gov/biosample?Db=biosample&DbFrom=bioproject&Cmd=Link&LinkName=bioproject_biosample&LinkReadableName=BioSample&ordinalpos=1&IdsFromResult=702962)

**Comment by pvangay** [comment]
SRA BioProject IDs for clarity:
PRJEB39497 (metaG)
PRJEB39495 (16S rRNA)
PRJEB39496 (fungal ITS)

**Comment by ssarrafan** [comment]
Next step will be documented in https://github.com/microbiomedata/NMDC_Planning/issues/67 for June
