### ISSUE TITLE
SFA - WSF: Watershed Function

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#53]
SFA initiation calls were scheduled in April and this issue is for having the first set of calls and attaching any details or information related to them here.

Adding for FYI: @mslarae13 @emileyfadrosh @corilo @SamuelPurvine @dehays @elishawc @mar-rudolph @kfagnan

**Comment by pvangay** [comment]
Met today to review datasets (jointly with TES SFA). Currently one dataset with metaG data available at JGI, with amplicon on the way, and biogeochemical data at ESS DIVE.

Also working on compiling metagenome data across CSPs with samples from a single watershed - will continue discussions on timeline and availability.

[Prelim Data](https://docs.google.com/spreadsheets/d/168SPpP2wOz3-WEHhprcZJMjzbDTQ76EjEyTheEJZUC0/edit)
[Call Notes](https://docs.google.com/document/d/11VQghyYb4Cf1kMD0ngB0-T8lqasdH7kUX-HZf92lr3o/edit)

**Comment by pvangay** [comment]
@dehays @mslarae13 the metaG data for this is available under JGI proposal id 505800 - please connect to see if there is missing metadata that you need.

**Comment by ssarrafan** [comment]
Next steps will be documented at https://github.com/microbiomedata/NMDC_Planning/issues/68 in June

**Comment by jagadishcs** [comment]
@pvangay 
Reviewed the biosamples of  ITS Proposal 505800 and shared for update in GOLD.
