### ISSUE TITLE
Review 3 FICUS datasets in the portal with PIs

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#54]
Meet with each PI group and review their data in the portal in detail. Specifically, make sure that their data looks correct. Identify metadata that should be exposed. And identify potential stories to include in the data highlights.

- [x] Wrighton
- [x] Stegen
- [x] Brodie

**Comment by pvangay** [comment]
Met with Reb Daly, notes here: https://github.com/microbiomedata/nmdc-server/issues/375

**Comment by mslarae13** [comment]
@pvangay 
Should/can we make sub tasks for each of these with a list of the tasks that need completed?

Ex: Update Wrighton dataset
-Update metadata sheet
-Send to Reb for confirmation
-Remove irrelevant samples

ect...?

**Comment by pvangay** [comment]
@mslarae13 I created a separate issue to capture the subtasks for each of the projects -- (see link above for Wrighton's). Figured they deserved their own issue (and assignee). Might end up spawning additional issues from that one but some decisions need to be made first. Hope this makes sense!

**Comment by pvangay** [comment]
Met with all three FICUS PIs and logged a bunch of issues for the June Sprint related to what we found.
