### ISSUE TITLE
Generate usage analytic reports for Twitter, Data Portal, Website

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_Planning#57]
- [x] Pull Twitter analytics, and Google Analytics for the data portal and the website (monthly or quarterly)
- [x] Generate a graph with usage data from all 3 sources
- [x] Identify outreach activities (tweets, newsletters, program announcements, publications) associated with peaks

**Comment by ssarrafan** [comment]
@Lebedeva-Sonya  says this issue is complete. She will add a link to the report here when she's back tomorrow and then we'll close this one.

**Comment by Lebedeva-Sonya** [comment]
[https://create.piktochart.com/output/54623051-v3-nmdc-google-analytics-report-copy-copy]
