### ISSUE TITLE
Metrics - Feedback and update

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#60]
This issue is to get feedback on the drafted metrics from the last sprint and to update/finalize the metrics. 

See https://github.com/microbiomedata/NMDC_Planning/issues/31 for more info.

**Comment by ssarrafan** [comment]
Removing Emiley and Set as Marisa has offered to own this issue.  Thank you @mar-rudolph

**Comment by mar-rudolph** [comment]
Initial draft of [metrics](https://docs.google.com/spreadsheets/d/1NEl8RuKffuvUm_Q4MLYcYMqSEDgkW15f2eyHttJfhlc/edit#gid=0) done. Will use an NMDC Sync in July to assign tracking duties and get the whole team on the same page.
