### ISSUE TITLE
Finalize IDEA Strategy

### ISSUE THREAD

**Issue by mar-rudolph** [microbiomedata/NMDC_Planning#62]

**Comment by mar-rudolph** [comment]
[NMDC IDEA Strategy](https://docs.google.com/document/d/1uHvQCP3q_1jgKeRDRnxIGRSoFzDSsCOdk9fTHZzm-5o/edit) draft complete, handed to working group for feedback. Aim to include in June newsletter

**Comment by ssarrafan** [comment]
> [NMDC IDEA Strategy](https://docs.google.com/document/d/1uHvQCP3q_1jgKeRDRnxIGRSoFzDSsCOdk9fTHZzm-5o/edit) draft complete, handed to working group for feedback. Aim to include in June newsletter

Congrats @mar-rudolph. Is it ok to close this issue?  I realize there will always be updates and refinements but for tracking purposes can we consider this done?

**Comment by mar-rudolph** [comment]
Final draft complete, next step: implementation!
