### ISSUE TITLE
SFA - WSF: Watershed Function 2

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#68]
Data is in IMG, proposal ID 505800, Jagadish to curate as needed, then pull out data for Montana. Montana to review metadata and contact PIs as needed.

**Comment by ssarrafan** [comment]
Continuation of issue https://github.com/microbiomedata/NMDC_Planning/issues/53 from May

**Comment by ssarrafan** [comment]
Please check your box when you've complete your part of this issue
- [ ] Jagadish pulls GOLD
- [ ] Montana sends template to user
- [ ] Montana and Jagadish match GOLD and EMSL analyses to user samples

**Comment by mslarae13** [comment]
Email sent requesting meeting to fill out metadata

**Comment by pvangay** [comment]
GOLD curation should be done. Reassigned to Montana to work with PIs.

**Comment by ssarrafan** [comment]
@pvangay said to close this issue since after meeting with them there is no data to work with right now.  Closing issue per mid-sprint review.
