### ISSUE TITLE
Expanded training materials for workflows and portal navigation

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#69]

**Comment by ssarrafan** [comment]
@pvangay I wanted to assign this to Julia but it doesn't appear that she has a GitHub account.  Should I invite her to GitHub?

**Comment by pvangay** [comment]
@ssarrafan weird! yes, absolutely, please add her!

**Comment by ssarrafan** [comment]
> @ssarrafan weird! yes, absolutely, please add her!

Ok I invited her so once she accepts we can re-assign this to her.

**Comment by pvangay** [comment]
Met with Julia today to discuss potential ideas for portal training. Plan is to build out a framework and work on a script for review, then record videos later in the month to account for feature updates.

**Comment by ssarrafan** [comment]
Julia hasn't accepted invite from GitHub. Sent her another invite and sent her note in Slack. Will keep assigned to myself for now.

**Comment by pvangay** [comment]
Ah thanks Set. I know she's out of the office this week but hopefully will
respond and get this taken care of next week.
--
Pajau Vangay, PhD (she/her)
Scientific Community Engagement Manager
National Microbiome Data Collaborative
Lawrence Berkeley National Laboratory
@microbiomedata <https://twitter.com/microbiomedata?lang=en> |
microbiomedata.org

**Comment by jkelliher-github** [comment]
Thanks Set for troubleshooting and figuring this out with me today! Everything should be all set now.


Julia


________________________________
From: pvangay ***@***.***>
Sent: Friday, June 11, 2021 3:03 PM
To: microbiomedata/NMDC_Planning
Cc: Kelliher, Julia Mae; Manual
Subject: [EXTERNAL] Re: [microbiomedata/NMDC_Planning] Expanded training materials for workflows and portal navigation (#69)


Ah thanks Set. I know she's out of the office this week but hopefully will
respond and get this taken care of next week.
--
Pajau Vangay, PhD (she/her)
Scientific Community Engagement Manager
National Microbiome Data Collaborative
Lawrence Berkeley National Laboratory
@microbiomedata <https://twitter.com/microbiomedata?lang=en> |
microbiomedata.org

**Comment by ssarrafan** [comment]
Checked with @jkelliher-github and closing this issue. Julia will add links to the materials to this issue.

**Comment by jkelliher-github** [comment]
https://docs.google.com/document/d/1Jyo-7z6taDHkltVrFPNyTEKlwLM7HyVm/edit
https://docs.google.com/spreadsheets/d/1fxiMX-3bXI6NTnw8CAgBvttz75YSCWRg8Kw5-ILtWwE/edit?pli=1#gid=0
https://drive.google.com/drive/folders/1z0v1Xs4LNzwqsYKKJhwOpYTtulJmgACL
