### ISSUE TITLE
Select Ambassadors cohort, plan for kick-off and trainings

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#73]

**Comment by pvangay** [comment]
6/1/21 - all materials have been given to reviewers. They have 2 weeks to review and we'll reconvene on 6/16 to make final selections.

**Comment by pvangay** [comment]
Finalists selected and notified. Non-selected emails have been sent out. Will not announce cohort until July. Continuing to plan and schedule kick-off meeting and trainings in July.

**Comment by pvangay** [comment]
Cohort has been finalized, and all have accepted. All meetings and trainings for the summer have been scheduled!
