### ISSUE TITLE
Validation of ENVO and GOLD terms

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_Planning#75]
Please move to more appropriate repository.

**Comment by turbomam** [comment]
@wdduncan tentatively suggesting moving to NMDC runtime

What terms require validation? IE from the MIxS triad?

**Comment by dwinston** [comment]
Yes, that's OK.

**Comment by cmungall** [comment]
@ssarrafan I'm not sure what kind of validation we are talking about. Is this the original ticket?
https://github.com/microbiomedata/nmdc-metadata/issues/309

or is this something different?

**Comment by ssarrafan** [comment]
> @ssarrafan I'm not sure what kind of validation we are talking about. Is this the original ticket?
> [microbiomedata/nmdc-metadata#309](https://github.com/microbiomedata/nmdc-metadata/issues/309)
> 
> or is this something different?

Hi @cmungall.  I added this issue based on a meeting with @emileyfadrosh. I just checked with her on this again and she said to go ahead and close this one since the work is happening in different GitHub issues.  Sorry if this caused any confusion.

**Comment by turbomam** [comment]
@ssarrafan @emileyfadrosh Thanks for the clarification. If you can let me know what other issues supercede this one, I'll have a better idea of where I should be contributing vs where I might be replicating somebody else's work.

**Comment by ssarrafan** [comment]
> @ssarrafan @emileyfadrosh Thanks for the clarification. If you can let me know what other issues supercede this one, I'll have a better idea of where I should be contributing vs where I might be replicating somebody else's work.

I just created this issue based on notes from meeting with Emiley.  I'll send you a note on Slack.
